# Generated by Django 5.1 on 2024-09-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_app', '0002_alter_coupon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name of the customer.', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the last name of the customer.', max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(help_text='Enter the phone number of the customer.', max_length=11, verbose_name='Phone Number')),
                ('source_x', models.FloatField(help_text="Enter the X coordinate of the customer's source location.", verbose_name='Source X Coordinate')),
                ('source_y', models.FloatField(help_text="Enter the Y coordinate of the customer's source location.", verbose_name='Source Y Coordinate')),
                ('destination_x', models.FloatField(help_text="Enter the X coordinate of the customer's destination.", verbose_name='Destination X Coordinate')),
                ('destination_y', models.FloatField(help_text="Enter the Y coordinate of the customer's destination.", verbose_name='Destination Y Coordinate')),
                ('trip_type', models.CharField(help_text='Enter the type of the trip (e.g., standard, premium).', max_length=20, verbose_name='Trip Type')),
                ('availability', models.BooleanField(help_text='Indicate if the customer is available for trips.', verbose_name='Availability')),
                ('wallet', models.FloatField(default=0, verbose_name='Wallet')),
                ('coupons', models.ForeignKey(help_text='Select the coupon associated with the customer.', on_delete=django.db.models.deletion.PROTECT, to='coupon_app.coupon', verbose_name='Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
