# Generated by Django 5.1 on 2024-08-21 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('source_x', models.FloatField()),
                ('source_y', models.FloatField()),
                ('destination_x', models.FloatField()),
                ('destination_y', models.FloatField()),
                ('trip_type', models.CharField(max_length=20)),
                ('availability', models.BooleanField()),
                ('coupons', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coupon_app.coupon')),
            ],
        ),
    ]
