# Generated by Django 5.1 on 2024-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.FloatField(default=1000.0, verbose_name='Wallet'),
        ),
    ]
