# Generated by Django 5.1 on 2024-08-21 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0002_alter_coupon_options_and_more'),
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='availability',
            field=models.BooleanField(help_text='Indicate if the customer is available for trips.', verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='coupons',
            field=models.ForeignKey(help_text='Select the coupon associated with the customer.', on_delete=django.db.models.deletion.PROTECT, to='coupon_app.coupon', verbose_name='Coupon'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='destination_x',
            field=models.FloatField(help_text="Enter the X coordinate of the customer's destination.", verbose_name='Destination X Coordinate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='destination_y',
            field=models.FloatField(help_text="Enter the Y coordinate of the customer's destination.", verbose_name='Destination Y Coordinate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='Enter the first name of the customer.', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Enter the last name of the customer.', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(help_text='Enter the phone number of the customer.', max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_x',
            field=models.FloatField(help_text="Enter the X coordinate of the customer's source location.", verbose_name='Source X Coordinate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_y',
            field=models.FloatField(help_text="Enter the Y coordinate of the customer's source location.", verbose_name='Source Y Coordinate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trip_type',
            field=models.CharField(help_text='Enter the type of the trip (e.g., standard, premium).', max_length=20, verbose_name='Trip Type'),
        ),
    ]
