# Generated by Django 5.1 on 2024-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_alter_customer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.FloatField(default=100000.0, verbose_name='Wallet'),
        ),
    ]
