# Generated by Django 5.1 on 2024-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_alter_customer_options_alter_customer_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='wallet',
            field=models.FloatField(default=0, verbose_name='Wallet'),
        ),
    ]
