# Generated by Django 5.1 on 2024-09-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupon_app', '0002_alter_coupon_options_and_more'),
        ('customer_app', '0001_initial'),
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_status', models.BooleanField()),
                ('trip_cost', models.FloatField()),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_app.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.driver')),
            ],
        ),
    ]
