# Generated by Django 5.1 on 2024-09-11 14:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapsi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
