# Generated by Django 5.1 on 2024-08-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapsi_app', '0002_remove_trip_id_trip_coupon_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Trip Id'),
        ),
    ]
