# Generated by Django 5.1 on 2024-08-21 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
        ('driver_app', '0001_initial'),
        ('tapsi_app', '0003_alter_trip_trip_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer', verbose_name='Trip Customer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.driver', verbose_name='Assigned Driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payment_status',
            field=models.BooleanField(verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_cost',
            field=models.FloatField(verbose_name='Cost of Trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Trip ID'),
        ),
    ]
