# Generated by Django 5.1 on 2024-08-21 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0002_alter_coupon_options_and_more'),
        ('customer_app', '0002_alter_customer_options_alter_customer_availability_and_more'),
        ('driver_app', '0002_alter_driver_options_alter_driver_car_color_and_more'),
        ('tapsi_app', '0004_alter_trip_options_remove_trip_coupon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={},
        ),
        migrations.AddField(
            model_name='trip',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon_app.coupon'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.customer'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_app.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='payment_status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
