# Generated by Django 5.1 on 2024-09-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name of the driver.', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Enter the last name of the driver.', max_length=50, verbose_name='Last Name')),
                ('car_color', models.CharField(help_text="Enter the color of the driver's car.", max_length=50, verbose_name='Car Color')),
                ('car_plate', models.CharField(help_text="Enter the plate number of the driver's car.", max_length=50, verbose_name='Car Plate Number')),
                ('phone_number', models.CharField(help_text='Enter the phone number of the driver.', max_length=11, verbose_name='Phone Number')),
                ('car_model', models.CharField(help_text="Enter the model of the driver's car.", max_length=50, verbose_name='Car Model')),
                ('wallet', models.FloatField(help_text="Enter the current balance in the driver's wallet.", verbose_name='Wallet Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
            },
        ),
    ]
