# Generated by Django 5.1 on 2024-09-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='wallet',
            field=models.FloatField(default=0.0, help_text="Enter the current balance in the driver's wallet.", verbose_name='Wallet Balance'),
        ),
    ]
