# Generated by Django 5.1 on 2024-09-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0002_alter_driver_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Driver Rating'),
        ),
    ]
